PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    password TEXT NOT NULL,
    UNIQUE(name)
);
CREATE TABLE IF NOT EXISTS devices (
    fingerprint TEXT NOT NULL PRIMARY KEY,
    user INTEGER,
    FOREIGN KEY (user) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS classes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    year INTEGER NOT NULL,
    division INTEGER NOT NULL,
    specialty TEXT NOT NULL,
    user INTEGER NOT NULL,
    FOREIGN KEY (user) REFERENCES users(id),
    UNIQUE(year, division, specialty, user)
);

CREATE TABLE IF NOT EXISTS subjects (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    teacher TEXT,
    hours INTEGER,
    class INTEGER NOT NULL,
    FOREIGN KEY (class) REFERENCES classes(id) ON DELETE CASCADE,
    UNIQUE(name,class)
);
CREATE TABLE IF NOT EXISTS students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    lastname TEXT NOT NULL,
    name TEXT NOT NULL,
    class INTEGER NOT NULL,
    FOREIGN KEY (class) REFERENCES classes(id) ON DELETE CASCADE
    UNIQUE(dni),
);
CREATE TABLE IF NOT EXISTS asistances (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student INTEGER NOT NULL,
    subject INTEGER,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    presence TEXT NOT NULL,
    FOREIGN KEY (student) REFERENCES students(id) ON DELETE CASCADE,
    FOREIGN KEY (subject) REFERENCES subjects(id) ON DELETE CASCADE
);